# Generated by Django 4.0.5 on 2022-06-24 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_calculation_calculatormemory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='calculator_memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calc_memory', to='calc.calculatormemory'),
        ),
    ]
